---
- name: Add Grafana GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    update_cache: yes

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes
  become: true

- name: Start Grafana service
  service:
    name: grafana-server
    state: started
    enabled: true
  become: true
